build:
    image: kradalby/ci-tox:latest
    pull: true
    environment:
      - DJANGO_SETTINGS_MODULE=init_django.settings.prod
    commands:
        - make env
        - make dev
        - make flake8
        - tox

notify:
    slack:
        webhook_url: https://hooks.slack.com/services/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
        channel: teknisk-dev
        username: drone
        when:
            branch: master

deploy:
  ssh:
    host: onyx.fap.no
    user: www
    port: 22
    when:
        branch: master
    commands:
      - cd /usr/local/www/p0sx.fap.no
      - git pull
      - export DJANGO_SETTINGS_MODULE=p0sx.settings.prod
      - make env
      - make prod
      - make migrate
      - make collect_static
      - supervisorctl restart uwsgi_p0sx.fap.no
