build:
    image: kradalby/ci-tox:latest
    pull: true
    environment:
      - DJANGO_SETTINGS_MODULE=init_django.settings.prod
    commands:
        - make env
        - make dev
        - make flake8
        - tox

notify:
    slack:
        webhook_url: https://hooks.slack.com/services/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
        channel: teknisk-dev
        username: drone
        when:
            branch: master

publish:
  docker:
    registry: registry.fap.no
    repo: p0sx/p0sx
    tag: latest
    insecure: true
    when:
        branch: master
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: latest
  docker:
    registry: registry.fap.no
    repo: p0sx/p0sx
    tag: $$TAG
    insecure: true
    when:
        event: tag
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: latest

deploy:
  ssh:
    host:
     - primeape.terra.fap.no
    user: root
    port: 22
    sleep: 3
    commands:
      - docker pull registry.fap.no/p0sx/p0sx:latest
      - docker-compose -f /srv/docker/p0sx/docker-compose.yml stop p0sx-dev
      - docker-compose -f /srv/docker/p0sx/docker-compose.yml up -d p0sx-dev
    when:
        branch: master
