# Generated by Django 3.2.25 on 2026-10-05 12:35

from django.db import migrations, models
import pos.models.sumup_cloud


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_auto_20251006_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='SumupAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(default=pos.models.sumup_cloud._get_nonce, editable=False, max_length=128)),
                ('refresh_token', models.TextField(null=True)),
                ('expiry', models.DateTimeField(null=True)),
            ],
        ),
    ]
